In [7]:
import numpy as np
arr = np.array([[3,3,4],[4,6,2],[4,7,6]])

In [10]:
arr.shape

(3, 3)

In [38]:
# 2 Qestion
import math
arr = np.array([1.1,2.2,3.3])
integer = [math.floor(x) for x in arr]
integer

[1, 2, 3]

In [20]:
# 3 Question 
arr = np.array([1,2,3,4,5,6])
arr[[1,3,5]]

array([2, 4, 6])

In [26]:
# 4 question
array = np.array([2,4,5,6,7,7,4,3,8])
array.reshape(3,3)

array([[2, 4, 5],
       [6, 7, 7],
       [4, 3, 8]])

In [34]:
# 5 question
arr = np.array([4,33,2444,322,43,21,788,87,87,988,68,98])
mask = arr>50
arr[mask]

array([2444,  322,  788,   87,   87,  988,   68,   98])