In [3]:
import numpy as np

In [11]:
arr = np.array([[2,4,5],[5,6,4],[5,7,6],[2,4,6]])
arr

array([[2, 4, 5],
       [5, 6, 4],
       [5, 7, 6],
       [2, 4, 6]])

In [19]:
flat = arr.flatten()
flat

array([2, 4, 5, 5, 6, 4, 5, 7, 6, 2, 4, 6])

In [23]:
flat[0]

np.int64(2)

In [27]:
flat[:4]

array([2, 4, 5, 5])

In [31]:
flat[5:]

array([4, 5, 7, 6, 2, 4, 6])

In [33]:
flat[::3]

array([2, 5, 5, 2])

In [35]:
flat[3] = 3434

In [39]:
flat

array([   2,    4,    5, 3434,    6,    4,    5,    7,    6,    2,    4,
          6])

In [43]:
flat[2:5].copy() # this is not a slice b/c we are using copy to get the copy

array([   5, 3434,    6])

In [50]:
arr = np.array([3,44,4,32,22,6,7,87,6,5,])
arr

array([ 3, 44,  4, 32, 22,  6,  7, 87,  6,  5])

In [54]:
arr[[2,3,5]]

array([ 4, 32,  6])

In [58]:
arr[arr>8]

array([44, 32, 22, 87])