In [11]:
import numpy as np
arr = np.array([2, 5, 2, 1, 6, 8, 9])
np.max(arr)


np.int64(9)

In [13]:
np.diff(arr)

array([ 3, -3, -1,  5,  2,  1])

In [17]:
np.percentile(arr, 50)  # For the 50th percentile (median)

np.float64(5.0)

In [19]:
np.mean(arr)

np.float64(4.714285714285714)

In [21]:
np.prod(arr)

np.int64(8640)

In [23]:
np.unique(arr)

array([1, 2, 5, 6, 8, 9])

In [25]:
np.diff(arr)

array([ 3, -3, -1,  5,  2,  1])

In [27]:
np.cumsum(arr)

array([ 2,  7,  9, 10, 16, 24, 33])