In [3]:
import numpy as np


In [13]:
!pip install numpy



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [23]:
array = np.array([2,4,6])
array

array([2, 4, 6])

In [29]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
np.full((4,3),3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [43]:
np.eye((9))

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [51]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [59]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [67]:
myarr = np.array([[2,4,5],[2,3,5],[2,6,5]])
myarr

array([[2, 4, 5],
       [2, 3, 5],
       [2, 6, 5]])

In [73]:
myarr.shape

(3, 3)

In [75]:
myarr.size

9

In [79]:
myarr.ndim

2

In [81]:
myarr.dtype

dtype('int64')

In [89]:
myarr = np.array([[2,4,5],[2,3,5],[2,6,5],[2,4,5]], dtype = float)

In [93]:
myarr

array([[2., 4., 5.],
       [2., 3., 5.],
       [2., 6., 5.],
       [2., 4., 5.]])

In [101]:
n = myarr.astype('float32')
n.dtype

dtype('float32')

In [119]:
myarr.dtype

dtype('float64')

In [124]:
reshape = myarr.reshape((6,2))
reshape

array([[2., 4.],
       [5., 2.],
       [3., 5.],
       [2., 6.],
       [5., 2.],
       [4., 5.]])

In [130]:
flattend = myarr.flatten()
flattend

array([2., 4., 5., 2., 3., 5., 2., 6., 5., 2., 4., 5.])